language: csharp
mono: none
dotnet: 3.1
env:
  - BUILD_BUILDNUMBER=$TRAVIS_BUILD_NUMBER
before_install:
  - nvm install stable
  - node --version
script:
  - dotnet restore
  - dotnet build
  - dotnet test
  - dotnet publish -o GoBoard/site && cd GoBoard/site && zip ../site.zip * && cd .. && zip ../aws-deploy.zip site.zip aws-windows-deployment-manifest.json
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "eu-west-2"
  app: "GoBoard"
  env: "Goboard-env"
  bucket: "elasticbeanstalk-eu-west-2-813514581751"
  zip_file: aws-deploy.zip
  on:
    branch: master
  edge: true
