language: csharp
mono: none
dotnet: 3.1
env:
  - BUILD_BUILDNUMBER=$TRAVIS_BUILD_NUMBER
script:
  - dotnet restore
  - dotnet build
  - dotnet test
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "eu-west-2"  
  app: "GoBoard"
  env: "Goboard-env"
  bucket_name: "elasticbeanstalk:eu-west-2:813514581751"
  on:
    branch: master
